### PR TITLE
refactoring/ 36 Changed naming convention of classes 

### LINKED ISSUE #36: Change Naming convention of classes
Change Naming convention of PrettySecureCould classes for example java.io.File exists and is a problem because we have also a File class. New naming convetion for PrettySecureClould would be "PscFile". The same is true for every conflict that accurs with the standard library

### PR DESCRIPTION
**Pull request by ridvan-sevimli**
Changed naming convention of classes to avoid conflicts with java standard library.  New convetion Psc.......

### CODE REVIEW

**Review by SandroGuerotto — APPROVED** [review]
OK. Für mich

**Review by ghost — APPROVED** [review]
passt 👌

**Comment by siebl** [comment]
👍 Danke fürs refactoring

**Review by siebl — APPROVED** [review]
👍 Danke fürs refactoring

**Pull request merged**
